## AdoptOpenJDK 停止发布 OpenJDK 二进制，而 Eclipse Temurin 是它的延伸，提供更好的稳定性
FROM eclipse-temurin:8-jre

## 创建目录，并使用它作为工作目录
USER root
RUN mkdir -p /data/spring-boot/config
WORKDIR /data/spring-boot

ARG JAR_WORK_PATH=/data/spring-boot
ARG JAR_PATH=./mgmt-controller
ARG JAR_LOG=/home/gzaccount/prodjar/ylxjar/mgmt-controller/log
ARG JAR_NAME=ylx-mgmt-controller-deploy-0.0.1-SNAPSHOT.jar
ARG JAR_PROFILE=DEV

RUN echo -e "\033[44;37m cd ${JAR_WORK_PATH} &&jar -Xmx1024M -Xms1024M -Dspring.profiles.active=${JAR_PROFILE} -jar ${JAR_PATH}/${JAR_NAME} \033[0m"

## 创建和挂载 数据目录和日志目录
RUN mkdir -p ${JAR_LOG}

## 将后端项目的 Jar 文件，复制到镜像中
COPY ${JAR_PATH:?error}/${JAR_NAME:?error} app.jar

## 设置 TZ 时区
## 设置 JAVA_OPTS 环境变量，可通过 docker run -e "JAVA_OPTS=" 进行覆盖
ENV TZ=Asia/Shanghai JAVA_OPTS="-Xmx1024M -Xms1024M -Dspring.profiles.active=${JAR_PROFILE:?error}"

## 暴露后端项目的  端口
EXPOSE 8080
## 暴露后端项目的 调试  端口
EXPOSE 5005

## 启动后端项目
CMD java ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar app.jar
